version: '3.9'
services:
  gfaster-service-main:  
    environment:
    - IMAGE=${IMAGE}"
    - CONTAINER_NAME=${CONTAINER_NAME}"
    - DEPLOY_ENVIRONMENT=${DEPLOY_ENVIRONMENT}"
    image: "$IMAGE"
    container_name: "$CONTAINER_NAME"
    labels:
      - "group=${DEPLOY_ENVIRONMENT}"
    restart: always
    tty: true
    stdin_open: true
