version: '3.9'

# networks:
#   taxonet:
#      external: true
#   bnet:
#      external: true     

services:
  gfaster-service-main:
    environment:
    - IMAGE=${IMAGE}"
    - CONTAINER_NAME=${CONTAINER_NAME}"
    - DEPLOY_ENVIRONMENT=${DEPLOY_ENVIRONMENT}"
    image: "$IMAGE"
    container_name: "$CONTAINER_NAME"
    labels:
      - "group=${DEPLOY_ENVIRONMENT}"
    # networks:
    #   - taxonet
    #   - bnet
    restart: always
    tty: true
    stdin_open: true
    # volumes:
    #   - /home/elbrick/docker-data/taxomarket:/data